name: 'GitHub Pages Deploy'
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: |
          npm ci
        env:
          CI: true
      - name: Build
        run: |
          npm run build
      - name: Deploy
        env:
          GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
        run: |
          cd src/.vuepress/dist
          git init
          git add -A
          git commit -m 'chore':' 🤖 GitHub Pages Deploy in Travis CI from ${GITHUB_SHA}'
          git push -f https://${GITHUB_DEPLOY_TOKEN}@github.com/FubukiNoCornField/fubukinocornfield.github.io.git master
